### ISSUE TITLE
Downloading Offline Tiles

### ISSUE THREAD

**Issue by jasonrogena** [onaio/kujaku#12]
Add a service for downloading offline tiles for a third party app in anticipation that the app will call the Kujaku map when offline. Bounds should be provided by the third-party app.

**Comment by ekigamba** [comment]
1. Create an Intent Service to handle the background downloading of required maps
1. Create a MapBox Offline Resources-Downloader to:
   - Download styles, icons & other map resources for offline use given the 
       - Bounds of the map
       - Style URL
       -  Name of the map
       -  Zoom levels
       -  Screen density
       -  Region metadata (For internal & identification purposes)
   - Delete a given offline map & it's resources
  

To figure out if the SDK actually does work automatically i.e. detect whenever there is an internet connection & manage any failed downloads of offline maps

**Comment by ekigamba** [comment]
![offline map download activity diagram](https://user-images.githubusercontent.com/31766075/33544963-c56ee95a-d8ed-11e7-93c4-5ce91ddecae0.jpg)
