### ISSUE TITLE
Feedback on Sample App 15 Oct 2018

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#126]
I reviewed the sample app that was supplied over the weekend. I tested it on both my Android Studio emulator and my tablet. Emulator is API v23 Tablet API version is v25.

Here are my notes:
![screenshot_20181015-222233](https://user-images.githubusercontent.com/6067053/46978036-a3f70180-d082-11e8-9619-ee6c60e2db28.jpeg)
- [ ] The offline download button worked on both tablets
- [ ] When I opened the Map Activity on the emulator it showed a blank screen. It worked on my tablet
- [ ] I saw the multicolored points on the map on my tablet
![screenshot_20181015-221909](https://user-images.githubusercontent.com/6067053/46978005-8b86e700-d082-11e8-9a7d-229ff68c7c63.jpeg)
- [ ] When I touched a point, the menu came up in the bottom
- [ ] When I touched the menu item it went back to the host app and displayed the JSON object
- [ ] I could scroll through the cards of objects on the map and it showed, but didn't highlight the point that was being displayed.
- [ ] The color coding wasn't quite clear, but that's not in scope for GWv1
- [ ] The back button works from the map view to the host application view
- [ ] In the main page, I swiped from the left and got a menu
![screenshot_20181015-222345](https://user-images.githubusercontent.com/6067053/46978027-9ccff380-d082-11e8-8038-3044b8db589e.jpeg)
- [ ] I touched Offline Regions and nothing displayed. This is not in scope for the GWv1
- [ ] I touched the Task Queue and a screen displayed, but it wasn't clear what this was used for.
![screenshot_20181015-222426](https://user-images.githubusercontent.com/6067053/46978090-cab53800-d082-11e8-9134-d7e2930330cb.jpeg)
- [ ] I touched Low-level add point and get a black screen with a point on it. When I hit done, the app stops working
![screenshot_20181015-222738](https://user-images.githubusercontent.com/6067053/46978052-ac4f3c80-d082-11e8-821f-b52ad809cdf9.jpeg)
- [ ] I touched Low-level Add Point - Location services and the map displayed.
- [ ] I touched done on this screen and nothing happened
![screenshot_20181015-222909](https://user-images.githubusercontent.com/6067053/46978062-b5400e00-d082-11e8-94b8-dbf7dfe64a0f.jpeg)
- [ ] I touched High Level Add Point and the map displayed
- [ ] I added a point and it dropped a point on the map. I could add as many as I wanted.
![screenshot_20181015-223046](https://user-images.githubusercontent.com/6067053/46978070-bb35ef00-d082-11e8-85e9-334428c1b151.jpeg)
- [ ] When I hit done, the add and done box disappeared. I tried to touch the new marker and it didn't show anything (This isn't needed for GWv1)
- [ ] I went back to the main activity and opened the Kujaku activity to see if my new point shows up and it didn't
![screenshot_20181015-223510](https://user-images.githubusercontent.com/6067053/46978104-d0ab1900-d082-11e8-8297-e8ffef572c6f.jpeg)

**Comment by ekigamba** [comment]
> I touched done on this screen and nothing happened

You need to click on **Go to My Location** so that the map can focus on your location, when satisfied with what the GPS is providing as your point, you can now click on **DONE** to drop the point

**Comment by craigappl** [comment]
> > > I touched done on this screen and nothing happened
> 
> > You need to click on **Go to My Location** so that the map can focus on your location, when satisfied with what the GPS is providing as your point, you can now click on **DONE** to drop the point
> 
Got it. Sorry I missed that step.
> > > I could scroll through the cards of objects on the map and it showed, but didn't highlight the point that was being displayed.
> 
> > This seems to happen but I can't reproduce it on the device on which I had an issue
> 
Here are the screenshots of touching multiple points:
First point (I'm expecting the dot to get bigger, change an icon or change color when this point is selected when I touch it)
![screenshot_20181016-220704](https://user-images.githubusercontent.com/6067053/47046086-33ff7e80-d149-11e8-8bda-fd7adcb5cc7d.jpeg)

I scrolled through the cards. and stopped on another card. When I touched the card, the card went white, but there is no visual indicator on the point.
![screenshot_20181016-220858](https://user-images.githubusercontent.com/6067053/47046284-a1131400-d149-11e8-8bee-5684469ddde4.jpeg)

> > > I went back to the main activity and opened the Kujaku activity to see if my new point shows up and it didn't
> 
> Should we be saving the points added?

Persisting the points is the responsibility of the Host Application. The GeoWidget's responsibility is to pass the points that were added back to the host application so they can be persisted. As far as I'm concerned this part of the acceptance criteria, but I will also ask @mberg and @ukanga to verify if we need to save points in the host application for this release of the GeoWidget.

**Comment by mlberg** [comment]
On the add point, we want the compass to work.  Ideally, it would take you to your location where you can add your point.  It doesn't seem to work now.

I think we should replace the Add and done buttons with a + icon.    After you add a point, the plus icon would reappear.

Great work so far! It's looking really good.
