### ISSUE TITLE
Initiate RealmDatabase other than in the Application class

### ISSUE THREAD

**Issue by ekigamba** [onaio/kujaku#150]
For the library to work with Offline map downloads, the host application either has to:

- Extend `KujakuApplication` and call `super(false)` in your `Application` constructor
- Initialise realm in the `Application` class with `io.ona.kujaku.data.realm.RealmDatabase.init(Context)`

I am guessing this could be done in the service or any other place in case it has not been initiated to make it easier for host applications to use

@vincent-karuri any ideas?

**Comment by vincent-karuri** [comment]
Please look at PR #154  which includes the refactor ideas we discussed
