### ISSUE TITLE
G1.7.2: Selection of a geographic object on a map - from vector tiles

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#168]
We want to be able to click on a building from MapBox.

In this case, we want to import the vector tiles from a third party system that was downloaded directly from the GeoWidget. The Geometry data comes from the vector tile.
![image](https://user-images.githubusercontent.com/6067053/47787564-86ee3f80-dccc-11e8-9d17-52cb4b42dddb.png)

Background:
- Mapbox compiles a bunch of layers as vector tiles and pushes them down to the client
- RoadStreet is a layer for example
- There is a building layer that we can or cannot toggle
- In the GeoWidget, we need to interact with the building layer in a map

Scenario:
- We have thousands of locations in a vector tile server
- These locations need to stream into the GeoWidget
- We need to be able to interact with each object in a particular layer

Prerequisites to Test:
- Download data from Zambia and upload them into MapBox
-

**Comment by craigappl** [comment]
This is required for GeoWidget version 2, but I don't know if it's required for Reveal. @mberg may be able to help.

**Comment by ekigamba** [comment]
From previous [discussions in this document](https://docs.google.com/document/d/14yDqTd3MJHOEImb28xIvchSIWMTEDQQfNfq5GOC2ps0/edit?pli=1), this seems to be already implemented in Mapbox

To support this, a listener(callback) for feature clicks on specific layers or using a filter on features will be created as defined [here](https://github.com/onaio/kujaku/issues/208)
