### ISSUE TITLE
Separate the style from the data in the GeoWidget

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#171]
We need a way to add a style template from the host application that can be referenced by the GeoJSON that's passed in from the host application. Each intervention type (IRS,MDA,ITN) have a different color schema for each task businessStatus. So, we want to style polygons as green if the businessStatus: Sprayed. Then, when we pass in the GeoJSON from the host application, the style information doesn't need to be passed in with it.

**Comment by ekigamba** [comment]
We will have a discussion on this about the possible strategies around this and what you had in mind

**Comment by craigappl** [comment]
The style and the data has to be pushed together if working with an activity, but this feature is available in the view.

**Comment by craigappl** [comment]
@ekigamba based on our discussion today, I will close this issue.
