### ISSUE TITLE
Research on having flat data structure in Mapbox - only one data source(unfiltered) with different data categories

### ISSUE THREAD

**Issue by ekigamba** [onaio/kujaku#178]
**WHY THIS ISSUE WAS CREATED?**
Some of the host applications would have to only serve data on one layer instead of having to filter data and place in different layers but have it show differently.

Is this possible?

**PROBLEM DESCRIPTION**

(what I know so far)Mapbox requires that data having different visual characteristics to be on different layers where each layer has it's own different styling properties. I haven't looked keenly at all Mapbox features but was wondering if it would be possible to have all data in one source file(unfiltered) but end up having different visual characteristics(styling) on a Mapbox map.

@mberg @dkwamboka @cKellyDesign @KipSigei @samwata @Janemesi Any ideas if this is achievable and how do we go about this on Mapbox?

**Comment by mlberg** [comment]
I don't want to create to much extra work but it would be great if we could reference a seperate json file (mapviz spec) to to define the properties of the style spec.   It would be really nice to be able to have a style spec that can be replicated across android and mobile.  I realize for our use case it will be pretty simple to configure this manually but I thinking having this as a config file would be really awesome.

Can you connect with @cKellyDesign to understand how gisida works and let us know if you think it's feasible?  Again, this is not a priority if time is an issue but would be good to support longer term.

**Comment by ekigamba** [comment]
Thanks @dkwamboka @mberg @cKellyDesign @KipSigei @samwata @Janemesi for you inputs.

My findings on the research:

- The following is possible currently on Mapbox as in this style https://www.mapbox.com/studio/styles/ona/cjo6w453f1wnb2sqoynwz40qp/edit/  in layer `red and blue kids - data conditions`

In a single layer and using a single data source, you can style data differently by using [expressions](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions) on feature data.

Below is an example of the usage in [this](https://www.mapbox.com/studio/styles/ona/cjo6w453f1wnb2sqoynwz40qp/edit/ ) style:

```json
    ...

        {
            "id": "red and blue kids - ",
            "type": "symbol",
            "source": "composite",
            "source-layer": "zeir-livingstone-data-2-kigamba",
            "filter": ["==", "$type", "Point"],
            "layout": {
                "icon-image": [
                    "step",
                    ["get", "is_red"],
                    "red-baby",
                    1,
                    "blue-baby"
                ],
                "icon-allow-overlap": true,
                "visibility": "none"
            },
            "paint": {}
        },
        {
            "id": "red and blue kids - data conditions",
            "type": "symbol",
            "source": "composite",
            "source-layer": "zeir-livingstone-data-2-kigamba",
            "filter": ["==", "$type", "Point"],
            "layout": {
                "icon-allow-overlap": true,
                "icon-image": [
                    "match",
                    ["get", "is_red"],
                    0,
                    "blue-baby",
                    [1], // is_red equal to 1
                    "red-baby", // the icon to apply
                    "" //fallback value
                ]
            },
            "paint": {}
        }

```

This uses the following expressions [https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-match](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-match) and [https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-step](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-step)

**Comment by ekigamba** [comment]
The issue here was solved and new discussion from https://github.com/onaio/kujaku/issues/178#issuecomment-436452109 moved to https://github.com/onaio/kujaku/issues/244
