### ISSUE TITLE
Prompt the user to turn on GPS if not enabled when they touch the my location button and add point button

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#188]
The GeoWidget needs to ask the user to turn on the GPS if it's not currently enabled when they touch the my location button and add point button. This should be a modal notification that pops up as is currently done in Google Maps.

Step1: View request
![screenshot_20181108-180844](https://user-images.githubusercontent.com/6067053/48238903-a72f9580-e381-11e8-8034-229f03e65ff0.png)
Step 2: Detailed view of which version of location services will be enabled.
![screenshot_20181108-180910](https://user-images.githubusercontent.com/6067053/48238947-d47c4380-e381-11e8-8535-81540fed3571.png)

**Comment by rowo** [comment]
@craigappl Yes this is fine. I think this is standard. Same as like when apps need access to photos or the mic, etc.
