### ISSUE TITLE
Offline map download auto-resumption needs attention

### ISSUE THREAD

**Issue by ekigamba** [onaio/kujaku#194]
It seems that if the network is disconnected or the internet is unavailable during an offline map download, the map download is stuck. The offline map download should resume once the internet connection is back. However, this does not seem to happen

**Comment by ekigamba** [comment]
The resumption seems to work well for a few minutes.
The resumption also works if you exit the app and come back since the download uses a foreground service that maintains the download progress notification on the notification bar.
When the internet is disconnected for around 11 minutes and resumed. It takes some minutes before the download progress bar starts showing progress.

From the logs the internet was disconnected at around **6:09 PM** and errors were logged by Mapbox at:

- 6:09 pm
- 6:11 pm
- 6:12 pm
- 6:14 pm
- 6:18 pm

The wifi was turned on at **6:22 pm** and the download did not start until **6:26 pm**.

This shows that Mapbox retries resuming the download after **1 min, 2 mins, 4 mins, 8 mins** and so on. The Mapbox `OfflineManager` however uses a broadcast receiver for `android.net.conn.CONNECTIVITY_CHANGE` which might not be utilised as expected from this observation

**Comment by ekigamba** [comment]
Offline map download resumption works OK when inside activities using the mapbox `MapView`. It seems that this is because the `MapView` **activates** the `com.mapbox.mapboxsdk.net.ConnectivityReceiver` and thus the

The Android MapboxSDK OfflineManager does not directly enable the `com.mapbox.mapboxsdk.net.ConnectivityReceiver` when offline region download resumes. It is only enabled when an offline region is being created and deactivated immediately after the region creation succeeds or fail. However, the `OfflineManager` and it's components use the `com.mapbox.mapboxsdk.net.ConnectivityReceiver`(which is a singleton) if it is activated.

The fix would be to activate the `com.mapbox.mapboxsdk.net.ConnectivityReceiver` before an `OfflineRegion` status is **activated** and **deactivated** after the OfflineRegion is done downloading, encounters a tile count limit exception or the `MapboxOfflineDownloaderService` is shutdown. Classes using the `MapboxOfflineResourcesDownloader` should deactivate the `ConnectivityReceiver` when they are destroyed to prevent a memory leak

**Comment by vincent-karuri** [comment]
![screenshot_20190306-175100](https://user-images.githubusercontent.com/33488286/53890506-65fe7800-4039-11e9-8ad2-0cc898e8373a.png)


Getting very many notification error messages when wifi is turned off when downloading map.

Samsung J5 physical phone.
