### ISSUE TITLE
Resize the my location widget on phones

### ISSUE THREAD

**Issue by githengi** [onaio/kujaku#223]
The current widget for show my location was developed for tabs. 

Its too large on phones and needs to support phones specific sizes

![image](https://user-images.githubusercontent.com/25123762/49518569-02d13e00-f8b0-11e8-9e27-fe28350ae9eb.png)

**Comment by ekigamba** [comment]
We are going to use the icon here https://material.io/tools/icons/?search=location&icon=my_location&style=baseline. @rowo is ok with it since it's the standard. The current one is a png with a drawable border

**Comment by rowo** [comment]
I left a comment on sizing on Slack. Guidelines say 56x56 for the regular floating action button and 40x40 for the mini version. I think the menu and my location can be that 40x40 size.
