### ISSUE TITLE
G3.4 Generate and View a Map with Foci Boundaries and Related Data

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#256]
Note: This issue is both related to Reveal and to the GeoWidget.

The goal of this issue is to display a map with multiple types of locations as well as a white boundary for the Focus Area. This will be achieved by 

Pass criteria:
- [ ] Multiple types of locations are displayed on the map with different styles (Point Residential Structures, Polygon Residential Structures, Point Mosquito Collection Points, Point Larval Breeding Sites)
- [x] Display a white boundary of the operational area on the map. Note that a focus in Reveal is the same as the operational area.
- [ ] Users should be able to touch on each location to display information on that location in the card view.

**Comment by armageddon** [comment]
Larval breeding sites may be polygons I think

**Comment by ekigamba** [comment]
@githengi, @vincent-karuri and I had a meeting on 6th February 2019
@githengi had the following definition of the feature:

```
Generating and viewing a map with foci boundaries and related data

- The Geo-widget should be able to draw foci boundaries like the ones on mSpray - the white circular boundaries and the label of the foci area
- The width and color should be configurable
- A GeoJSON should be passed to define foci boundaries to be drawn
- The boundary should not disappear when zoomed out - We should provide support/configurability for this
- The label should be the name of the foci boundary and  should not disappear when zoomed out 
- The label text size, color (probably other formatting options) should be configurable

```

**Comment by ekigamba** [comment]
It is possible to create such kind of boundaries out of the box on Mapbox using the `LineLayer` for the boundaries and `SymbolLayer` for the labels. Is this something that we should think about implementing any more on the library. Both layers can also be accessed from the android SDK.

**Comment by ekigamba** [comment]
@craigappl 

> - [ ] Multiple types of locations are displayed on the map with different styles (Point Residential Structures, Polygon Residential Structures, Point Mosquito Collection Points, Point Larval Breeding Sites)

**Host application configuration through the style**

> - [ ]  Display a white boundary of the operational area on the map. Note that a focus in Reveal is the same as the operational area

**Implemented currently as a `Boundary Layer` in the Geo-Widget** https://github.com/onaio/kujaku/pull/267

> - [ ]  Users should be able to touch on each location to display information on that location in the card view.

 **Implemented on the host application using the `onFeatureClickListener` or (Mapbox SymbolLayerInfo window / Mapbox Info Window)**

**Comment by craigappl** [comment]
Those sound fine to me. I think we just need to document the feature somewhere.
