### ISSUE TITLE
G3.8 Filter Cases on the Map

### ISSUE THREAD

**Issue by craigappl** [onaio/kujaku#259]
The host application will need the ability to filter locations on the map based on business logic.

Pass Criteria:
- [ ] The host application can filter based on the type of location
- [ ] The host application can pass an array or list of locations to display and all other locations will be removed from the view

**Comment by ekigamba** [comment]
This seems to be related to https://github.com/onaio/kujaku/issues/237 to some point.

Currently only `equalTo` and `regex` filters for data type `String` are going to be implemented
