### ISSUE TITLE
Handle null locations on getLastLocation and remove stale last locations

### ISSUE THREAD

**Issue by ekigamba** [onaio/kujaku#263]
This seems that it can happen on rare occasions
https://developer.android.com/training/location/retrieve-current#java

- [x] Handle null locations after calling `getLastLocation` on the `FusedLocationClient`
- [x] Reset `lastLocation` to null if the `location services` or location on the device has been turned off
- [x] Improve `last location` and `location updates` accuracy and suitability by using the algorithm provided by google https://developer.android.com/guide/topics/location/strategies#BestEstimate
- [x] To be able to save battery, once an accurate location have been retrieved. Can the Geowidget support a way for the host app to reduce the frequency of updates? This will be configurable after the initial default setup of update intervals to support throttling down update requests with an aim to reduce on power consumption

As requested by @githengi

**Comment by githengi** [comment]
To be able to save battery, once an accurate location have been retrieved. Can the Geowidget support a way for the host app to increase the frequency of updates.

https://developer.android.com/guide/topics/location/strategies#set-the-location-providers-to-return-updates-less-frequently

**Comment by ekigamba** [comment]
You mean decrease the frequency of updates?

**Comment by githengi** [comment]
Yes

**Comment by ekigamba** [comment]
Should we do that out-of-the-box or should that be something that is configurable by a host application if it wants that? I am thinking of a standard way to do that. I do not know if this should be the standard out-of-the-box?

Can you also provide the numbers in terms of updateIntervals that you are thinking about?

**Comment by githengi** [comment]
This can be configurable to the host application. The host application can should be able to setup updateIntervals
