### ISSUE TITLE
Parse 3rd Party App MapBox Style

### ISSUE THREAD

**Issue by jasonrogena** [onaio/kujaku#8]
Add functionality for parsing and rendering MapBox style JSON from the calling app.

1. Create MapBox Style GeoJSON on the 3rd party app
2. Pass the GeoJSON Data to Kujaku with the MapBox Style to merge with
3. Render the final style on the Kujaku MapView

**Comment by ekigamba** [comment]
3. Rendering the final style on the Kujaku MapView

- Get the MapBox Style:
   1. JSON String
   1. File path to Style 
       - Get the Style
- Set the style on the MapView

**Comment by ekigamba** [comment]
Update OpenSRP ZEIR Support Libraries to v24
